# yaml-language-server: $schema=https://raw.githubusercontent.com/TheDragonCode/preview-updater/refs/heads/main/resources/schema.json

image:
    parameters:
        packageManager: 'none'
        icon: 'photograph'
